import pytest
import importlib.util
import os
from tru import Verify

SHARDS_DIR = 'shards'

@pytest.mark.parametrize('shard_file', [
    'AirLeak_eqn_3_06.py',
    'AirLeak_eqn_4_07.py',
    'FluidFlowVacuumLines_eqn_1_13b.py',
    'FluidFlowVacuumLines_eqn_2_01.py',
    'FluidFlowVacuumLines_eqn_2_02.py',
    'FluidFlowVacuumLines_eqn_2_03.py',
    'FluidFlowVacuumLines_eqn_2_04.py',
    'FluidFlowVacuumLines_eqn_2_05.py',
    'FluidFlowVacuumLines_eqn_2_06.py',
    'FluidFlowVacuumLines_eqn_2_07.py',
    'FluidFlowVacuumLines_eqn_2_08.py',
    'FluidFlowVacuumLines_eqn_2_10.py',
    'FluidFlowVacuumLines_eqn_2_11.py',
    'FluidFlowVacuumLines_eqn_2_12.py',
    'FluidFlowVacuumLines_eqn_2_13.py',
    'FluidFlowVacuumLines_eqn_2_14.py',
    'FluidFlowVacuumLines_eqn_2_15.py',
    'FluidFlowVacuumLines_eqn_2_17.py',
    'LiquidRing_eqn_10_01.py',
    'LiquidRing_eqn_10_02.py',
    'LiquidRing_eqn_10_03.py',
    'LiquidRing_eqn_10_04.py',
    'LiquidRing_eqn_10_05.py',
    'LiquidRing_eqn_10_06.py',
    'LiquidRing_eqn_10_08.py',
    'LiquidRing_eqn_10_09.py',
    'LiquidRing_eqn_10_10.py',
    'LiquidRing_eqn_10_11.py',
    'LiquidRing_eqn_10_12.py',
    'LiquidRing_eqn_10_13.py',
    'LiquidRing_eqn_10_14.py',
    'LiquidRing_eqn_10_15.py',
    'LiquidRing_eqn_10_16.py',
    'LiquidRing_eqn_10_17.py',
    'LiquidRing_eqn_10_18.py',
    'LiquidRing_eqn_10_19.py',
    'LiquidRing_eqn_10_20.py',
    'LiquidRing_eqn_9_05.py',
    'Precondensors_eqn_6_11a.py',
    'Precondensors_eqn_7_01.py',
    'Precondensors_eqn_7_02.py',
    'Precondensors_eqn_7_03.py',
    'Precondensors_eqn_7_04a.py',
    'Precondensors_eqn_7_04aa.py',
    'Precondensors_eqn_7_04ab.py',
    'Precondensors_eqn_7_04ac.py',
    'Precondensors_eqn_7_05.py',
    'Precondensors_eqn_7_06.py',
    'Precondensors_eqn_7_07.py',
    'Precondensors_eqn_7_08.py',
    'Precondensors_eqn_7_09.py',
    'Precondensors_eqn_7_10.py',
    'Precondensors_eqn_7_11.py',
    'Precondensors_eqn_7_12.py',
    'Precondensors_eqn_7_14a.py',
    'Precondensors_eqn_7_14b.py',
    'Precondensors_eqn_7_15.py',
    'Precondensors_eqn_7_16.py',
    'Precondensors_eqn_7_17.py',
    'PressMgmt_eqn_2_17.py',
    'PressMgmt_eqn_3_01.py',
    'PressMgmt_eqn_3_02.py',
    'PressMgmt_eqn_3_03.py',
    'PressMgmt_eqn_3_04.py',
    'PressMgmt_eqn_3_05.py',
    'ProcessApp1_eqn_4_10.py',
    'ProcessApp1_eqn_5_01.py',
    'ProcessApp1_eqn_5_02a.py',
    'ProcessApp1_eqn_5_02b.py',
    'ProcessApp1_eqn_5_03.py',
    'ProcessApp1_eqn_5_04.py',
    'ProcessApp1_eqn_5_05.py',
    'ProcessApp1_eqn_5_06.py',
    'ProcessApp1_eqn_5_07.py',
    'ProcessApp1_eqn_5_08.py',
    'ProcessApp1_eqn_5_09.py',
    'ProcessApp1_eqn_5_10a.py',
    'ProcessApp1_eqn_5_10b.py',
    'ProcessApp1_eqn_5_10c.py',
    'ProcessApp1_eqn_5_11.py',
    'ProcessApp1_eqn_5_12.py',
    'ProcessApp1_eqn_5_13.py',
    'ProcessApp1_eqn_5_14.py',
    'ProcessApp1_eqn_5_15.py',
    'ProcessApp1_eqn_5_16.py',
    'ProcessApp2_eqn_5_17.py',
    'ProcessApp2_eqn_6_01.py',
    'ProcessApp2_eqn_6_02.py',
    'ProcessApp2_eqn_6_04.py',
    'ProcessApp2_eqn_6_06.py',
    'ProcessApp2_eqn_6_07.py',
    'ProcessApp2_eqn_6_08.py',
    'ProcessApp2_eqn_6_09.py',
    'ProcessApp2_eqn_6_10.py',
    'RotaryPistonVane_eqn_10_21.py',
    'RotaryPistonVane_eqn_11_01.py',
    'RotaryPistonVane_eqn_11_02.py',
    'RotaryPistonVane_eqn_11_03.py',
    'RotaryPistonVane_eqn_11_04.py',
    'RotaryPistonVane_eqn_11_05.py',
    'RotaryPistonVane_eqn_11_06.py',
    'SelectingPump_eqn_7_18.py',
    'SelectingPump_eqn_8_01.py',
    'SelectingPump_eqn_8_02.py',
    'SelectingPump_eqn_8_03.py',
    'SelectingPump_eqn_8_04.py',
    'SelectingPump_eqn_8_05.py',
    'SelectingPump_eqn_8_06.py',
    'SelectingPump_eqn_8_07.py',
    'SelectingPump_eqn_8_08.py',
    'SteamJetInjectors_eqn_8_09.py',
    'SteamJetInjectors_eqn_9_01.py',
    'SteamJetInjectors_eqn_9_02.py',
    'SteamJetInjectors_eqn_9_03.py',
    'SteamJetInjectors_eqn_9_04.py',
    'VacuumTheory_eqn_1_03.py',
    'VacuumTheory_eqn_1_07.py',
    'VacuumTheory_eqn_1_08.py',
    'VacuumTheory_eqn_1_09.py',
    'VacuumTheory_eqn_1_10.py',
    'VacuumTheory_eqn_1_11.py',
    'VacuumTheory_eqn_1_12.py',
    'VacuumTheory_eqn_1_13a.py',
])
def test_shard_consistency(shard_file):
    shard_path = os.path.join(SHARDS_DIR, shard_file)
    module_name = shard_file[:-3]
    spec = importlib.util.spec_from_file_location(module_name, shard_path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    
    for name, obj in module.__dict__.items():
        if isinstance(obj, type) and name != 'Verify':
            v = Verify(obj)
            res = v.verify()
            for eqn, variants in res.items():
                if not variants: continue
                valid_scores = [s for s in variants.values() if s is not None]
                if not valid_scores: continue
                max_score = max(valid_scores)
                for var, score in variants.items():
                    assert score == max_score, f'Equation {eqn} variant {var} is inconsistent (score {score}/{max_score})'
